name: space_galaxy_shooter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.1.1
  http: ^1.2.1
  flame: ^1.16.0
  flame_audio: ^2.10.0
  mongo_dart: ^0.10.0
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
